# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: api
generate:
  std-http-server: true
  strict-server: true
  models: true
output-options:
  nullable-type: true
output: internal/api/server.gen.go
