services:
    dev:
        build:
            context: .
        user: dev
        stdin_open: true
        tty: true
        volumes:
            - ..:/home/dev/working_dir
        working_dir: /home/dev/working_dir

    postgres:
        image: postgres:17.5
